spring:
  application:
    name: CoHab-chat

  threads:
    virtual:
      enabled: true

  mongodb:
    uri: mongodb://localhost:27017/cohab_chat

  kafka:
    bootstrap-servers: localhost:9092

  r2dbc:
    username: events
    password: events
    url: r2dbc:clickhouse://localhost:8123/events


  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      auto-index-creation: true

  rsocket:
    server:
      port: 7000
      mapping-path: "/rsocket"
      transport: "websocket"

  security:
    jwt:
      public-key: classpath:certs/public.pem

  liquibase:
    url: jdbc:clickhouse://localhost:8123/events
    user: events
    password: events
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true


server:
  port: 8080

kafka:
  topics:
    notification: "notification"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    enabled: true
  show-actuator: true
  writer-with-default-pretty-printer: true

logging:
  level:
    root: INFO
    by.magofrays: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
