spring:
  application:
    name: CoHab-chat

  data:
    mongodb:
      uri: mongodb://localhost:27017/cohab_chat
      auto-index-creation: true


  rsocket:
    server:
      port: 0
      mapping-path: "/rsocket"
      transport: "websocket"

  security:
    jwt:
      public-key: classpath:certs/public.pem


server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    enabled: true
  show-actuator: true
  writer-with-default-pretty-printer: true

logging:
  level:
    root: INFO
    by.magofrays: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

#websocket:
#  relay:
#    host: localhost
#    port: 61613
#    enabled: false
